# Copyright (C) 2024 Project-ACT
# 
# This file is part of be-graph-local-py.
# 
# be-graph-local-py is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# be-graph-local-py is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with be-graph-local-py.  If not, see <https://www.gnu.org/licenses/>.
---
title: "[External Defect]: Edit title after colon"
labels:
  - extern
  - defect
  - cp-be
  - triage
body:
  - type: markdown
    id: discussion_head_title
    attributes:
      value: "# External Defect"

  - type: markdown
    id: discussion_head_description
    attributes:
      value: |
        Please use this Discussion Category to describe an issue, problem, or defect
        you have encountered developing or interacting with this Component Project.

        We presume here that you are somewhat familiar with the details of this Component
        Project, its implementation, and the Initiative elements (User Stories, etc) on
        which it is based so that you can connect what you are seeing with what you
        should be seeing, and so that you know that this is the correct component project
        around which to begin this discussion.

        At the same time, a presumption that you are not a part of the team(s) working on
        the Initiative or its Component parts, thus *External*.

        Please take a moment to fill this in, your GitHub credentials will be used to
        attribute your contribution to this component project, and to the overall initiative,
        unless you would rather opt out.

  - type: markdown
    id: discussion_shortdesc_title
    attributes:
      value: "## Short Description"

  - type: markdown
    id: discussion_shortdesc_description
    attributes:
      value: |
        The text entered here will be visible via mouse over in GitHub issue summary views
        and may be extracted with automated tools for other uses.

        Please be succinct, one paragraph.
        
  - type: textarea
    id: shortdesc
    attributes:
      label: Brief Description
      description: Augments the issue title with an extended description

    validations:
      required: true

  - type: markdown
    id: discussion_characterization_title
    attributes:
      value: "## Characterization" 

  - type: markdown
    id: discussion_characterization_description
    attributes:
      value: |

        So that we can assess severity and priority scores, select at least one
        of each item in the checkbox blocks below, for Observations and for
        Frequency.

        If you have more detail for these, please include it down below.

  - type: markdown
    id: observations
    attributes:
      label: Observations
      description: Types of problems or failures observed
      options:
        - label: "Data Loss or Destructive Failure"
        - label: "Crash or other self-contained Failure"
        - label: "Unexpected behavior"
        - label: "Explicitly incorrect behavior"
        - label: "Does not meet expectations"
        - label: "Untestable"
        - label: "Cosmetic failure"
        - label: "Security failure"
        - label: "Privacy failure"


  - type: markdown
    id: frequency
    attributes:
      label: Frequency
      description: Reproducing the observations
      options:
        - label: "Observed nearly 100% of the time"
        - label: "Frequently but not consistently"
        - label: "Infrequently but observable"
        - label: "Difficult to observe, for unknown reasons"
        - label: "Seems to depend on external factors"

  - type: markdown
    id: discussion_usertype_title
    attributes:
      value: "## Me as User"

  - type: checkboxes
    id: usertype
    attributes:
      label: User Type (I am a …)
      description: Use context in which this bug was encountered
      options:
        - label: "**Unknown** user type, possibly not provided"
        - label: "**User Type A** description"
        - label: "**User Type B** description"
        - label: "**User Type C** description"
        - label: "**Any or All** user types listed above"


  - type: markdown
    id: discussion_environment_title
    attributes:
      value: "## Environment"

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Device, other configuration details
      placeholder: |
        - OS, Device(s), Platform(s), versions
        - Runtime environment
        - Other useful details to replicate your setup

    validations:
      required: true


  - type: markdown
    id: discussion_description_title
    attributes:
      value: "## Full Description"

  - type: textarea
    id: description
    attributes:
      label: Full Description
      description: Detailed description include reproducibility, specific parameters, and so on
      placeholder: |
        Try to be as specific and detailed as possible so that the circumstances of the bug
        as encountered can be reproduced for debugging and fixing. There will like be continued
        discussion as examination commences and continues.

    validations:
      required: true
